def getIcons():
    return {
        'user':'',
        'terminal':'',
        'code':'',
        'folder':'',
        'battery': ['', '', '', '' ],
        'charging': "",
        'power': '', 
        'screen_lock':'',
        'reboot': '',
        'logout': '',
        'columns': 'HHH',
        'monadtall': '[]=',
        'monadwide': 'TTT',
        'max': '[ ]',
        'treetab': '|[]',
        'volume':['', '', ''],
        'mute':'',
        'music':'',
        'temperature':'',
        'locks':'',
        'utilization':'',
        'wlan':'',
        'lan':'',
        'clock':'',
        'launch':'',
        'down':"",
        'up':"",
        'cancel':'',
        'error':'',
        'mail': '',
        'download':'',
        'backlight': ''
    }
