[global]
    workgroup = WORKGROUP
    server string = jMach
    server role = standalone server
    hosts allow = 192.168.50. 127.
    log file = /var/log/samba/%m.log
    logging = systemd
    follow symlinks = yes
    wide links = yes
    fruit:copyfile = yes

[Media]
    path = /home/job/Media
    read only = no
    writeable = yes
    create mask = 0774
