terminal_colors: "! special
    *.foreground:   #b6a28e
    *.background:   #0c080d
    *.cursorColor:  #b6a28e

    ! black
    *.color0:       #0c080d
    *.color8:       #9e9892

    ! red
    *.color1:       #911728
    *.color9:       #b72520

    ! green
    *.color2:       #82475e
    *.color10:      #82475e

    ! yellow
    *.color3:       #ba5622
    *.color11:      #fa752f

    ! blue
    *.color4:       #224260
    *.color12:      #2087e6

    ! magenta
    *.color5:       #94605d
    *.color13:      #ff857e

    ! cyan
    *.color6:       #7b8689
    *.color14:      #21cfff

    ! white
    *.color7:       #b6a28e
    *.color15:      #b6a28e"
wallpaper: "shuttle.png"
bodyfg: "white"
bodybg: "magenta"
titlefg: "white"
titlebg: "bright_red"
focusedfg: "white"
focusedbg: "bright_red"
urgentfg: "white"
urgentbg: "bright_yellow"
altfg: "white"
altbg: "yellow"
gradient:
    - "yellow"
    - "bright_green"
    - "yellow"
    - "bright_red"
    - "blue"
    - "magenta"
    - "green"
moduleseparator: ""
wspadding: 0
background: "00000000"
leftmoduleprefix: ""
leftmodulesuffix: ""
rightmoduleprefix: ""
rightmodulesuffix: ""
titlepadding: 5
bodypadding: 7
modulepadding: 4
focusedwindowborder: "green"
windowborder: "background"
barleftborder : 10
barrightborder : 10
bartopborder : 3
barbottomborder : 0
blurwallpaper: True
