terminal_colors: "pywal"
wallpaper: "shuttle.png"
bodyfg: "white"
bodybg: "magenta"
titlefg: "white"
titlebg: "bright_red"
focusedfg: "white"
focusedbg: "bright_red"
urgentfg: "white"
urgentbg: "bright_yellow"
altfg: "white"
altbg: "yellow"
gradient:
    - "bright_green"
    - "bright_yellow"
    - "yellow"
    - "bright_red"
    - "blue"
    - "magenta"
    - "green"
moduleseparator: ""
wspadding: 0
background: "00000000"
leftmoduleprefix: ""
leftmodulesuffix: ""
rightmoduleprefix: ""
rightmodulesuffix: ""
titlepadding: 0
bodypadding: 1
focusedwindowborder: "green"
windowborder: "background"
barleftborder : 10
barrightborder : 10
bartopborder : 3
barbottomborder : 0
